---
# Defaults for HAProxy backend IPs used by swl4AppInstall
# These preserve current behavior; override in inventory as needed.
bootstrap_ip: 192.168.41.227

master_ips:
  - 192.168.41.221
  - 192.168.41.222
  - 192.168.41.223

worker_ips:
  - 192.168.41.224
  - 192.168.41.225
  - 192.168.41.226
